### ISSUE TITLE
My friends dont have an amongus.exe file in their among us folder

### ISSUE THREAD

**Issue by vaszoly** [Narua2010/AmongUsModUpdater#13]
Yes i know this isnt really an issue with the product itself, but i see no reason as to why there isnt one, anyone know?

**Comment by Narua2010** [comment]
Have you purchased and installed the game via Steam?
Or does the question refer to the selection in AmongUs Mod Updater?
In the updater, the exe is unfortunately not currently displayed in the selection, but the exe exists in the corresponding folder. If the folder is selected, it usually works (as long as the exe is there anyway).

**Comment by ccir2429** [comment]
If you purchased Among us via Steam, you can go to your Steam library -> right click Among Us -> Properties ->Local files  and click on the "Verify integrity of game files..." button. this should fix the install and therefore add the missing Among Us.exe
