### ISSUE TITLE
[improvement] Search for among us path in windows registry

### ISSUE THREAD

**Issue by ccir2429** [Narua2010/AmongUsModUpdater#15]
If the game has been installed trough Steam, it is more efficient to search for the steam installPath value in the windows registry. From there, all you have to do is search the \steamapps\common\ to find the Among Us folder and application file.

I have an open PR that shows what I mean by that.
#14

**Comment by Narua2010** [comment]
I like the idea very much, and am looking at it right now - unfortunately for me it uses C:/%/steamapps/common

But the game is on D:/%/steamapps/common

I'll be happy to look at it and incorporate it though, as I think it's really good.
