### ISSUE TITLE
Among Us The_Other_Roles download is not working

### ISSUE THREAD

**Issue by vivixna** [Narua2010/AmongUsModUpdater#18]
Hello all:)

I can download the zip file, but it does not appear as a zip file. Therefore, the tutorial that I had found does not work. Is it possibly that it's because I want to download it and play it on a MacBook Air M1?

If so would it be possible to make the_other_roles for Apple? For example, so that people who want to play it on a MacBook can play the mod? That would be great. Because on the MacBook you can download the iPad app and play Among Us. 

Kind regards

**Comment by Narua2010** [comment]
Hey @vivixna ,

unfortunately the ModUpdater only works on windows. If you want to play on apple you should check [The Other Roles](https://github.com/Eisbison/TheOtherRoles) if the mod works on mac.

Kind regards
